server:
  port: 8001

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://39.108.157.35:3306/easy_bi_system?serverTimezone=GMT%2B8
          username: root
          password: 123456@zhiyi
          driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 39.108.157.35
    password: 123456
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.226.72:8848
        group: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
