mybatis-plus:
  # ?????????????? resultType ??????
  type-aliases-package: com.example.demo.pojo
  # ????sql?????????????????????
  mapper-locations: classpath:/mappers/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis-plus??
    cache-enabled: true #??????

spring:
  #redis??
  redis:
    host: 192.168.1.100
    port: 6379
    timeout: 5000 #????????????
    password: 123456
  datasource:
    url: jdbc:mysql://192.168.1.100/simpleBI?useUnicode=true&zeroDateTimeBehavior=round&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    click:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://192.168.1.100:9000
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000